In [1]:
import numpy as np

In [2]:
L = [0]*50000000

In [3]:
import random

In [7]:
L[random.randint(0,50000000-1)] = 1
L[random.randint(0,50000000-1)] = 2
L[random.randint(0,50000000-1)] = 3

In [16]:
def summ(L):
    s =0
    for x in L:
        s += x
    return s

In [17]:
summ(L)

6

In [18]:
%timeit -r1 -n1 summ(L)

4.15 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [19]:
sum(L)

6

In [21]:
%timeit -r1 -n1 sum(L)

604 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [51]:
A = np.array(L)

In [52]:
np.sum(A)

6

In [55]:
%timeit A.sum()

26.9 ms ± 486 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [81]:
X = np.array([[1,5,7],[2,4,8],[1,-1,-2],[0,5,0],[1,1,1]])

In [82]:
X

array([[ 1,  5,  7],
       [ 2,  4,  8],
       [ 1, -1, -2],
       [ 0,  5,  0],
       [ 1,  1,  1]])

In [84]:
X[1:4]

array([[ 2,  4,  8],
       [ 1, -1, -2],
       [ 0,  5,  0]])

In [85]:
X[1:3, 1:3]

array([[ 4,  8],
       [-1, -2]])

In [86]:
X.sum()

33

In [87]:
X.sum(axis=0), X.sum(axis=1)

(array([ 5, 14, 14]), array([13, 14, -2,  5,  3]))

In [88]:
X.max()

8

In [89]:
X.min()

-2

In [91]:
X.mean(axis=1)

array([ 4.33333333,  4.66666667, -0.66666667,  1.66666667,  1.        ])

In [92]:
X.flatten()

array([ 1,  5,  7,  2,  4,  8,  1, -1, -2,  0,  5,  0,  1,  1,  1])

In [93]:
X.reshape((3,5))

array([[ 1,  5,  7,  2,  4],
       [ 8,  1, -1, -2,  0],
       [ 5,  0,  1,  1,  1]])

In [96]:
type(X)

numpy.ndarray

In [102]:
X =np.array([[1, 2],[3,-1]])

In [103]:
X

array([[ 1,  2],
       [ 3, -1]])

In [116]:
v = np.array([-1,5])
v = v.reshape((2,1))
v

array([[-1],
       [ 5]])

In [113]:
X*v

array([[-1, -2],
       [15, -5]])

In [138]:
X.dot(v)

array([[1],
       [3]])

In [118]:
X.dot(v).shape

(2, 1)

In [126]:
table = np.arange(0, 2*np.pi+0.1, np.pi/6)
table

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653, 6.28318531])

In [130]:
np.exp(table)

array([  1.        ,   1.68809179,   2.84965391,   4.81047738,
         8.1205274 ,  13.70819567,  23.14069263,  39.06361336,
        65.9429652 , 111.31777849, 187.9146285 , 317.21714253,
       535.49165552])

In [132]:
cos = np.cos
sin = np.sin
pi = np.pi

In [133]:
R = np.array([[cos(pi/6), -sin(pi/6)], [sin(pi/6), cos(pi/6)]])

In [134]:
r

NameError: name 'r' is not defined

In [135]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [137]:
v = np.array([[1],[0]])
v

array([[1],
       [0]])

In [140]:
R.dot(v)

array([[0.8660254],
       [0.5      ]])