In [1]:
import numpy as np

In [79]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [3]:
x = np.array([[1],[0]])

In [5]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [6]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [7]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [5]:
perviy = R.dot(x)
R.dot(perviy)

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец v, с координатами 0 по иксу, 2 по игреку. Вычислите вектор-столбец w как результат поворота v на 30 градусов при помощи матрицы R

In [10]:
v = np.array([0,2]).reshape(2,1)
w = R.dot(v)
w

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R.

In [83]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию `Prod(x,y)`, которая вовращает скалярное произведение векоторов-столбцов `x` и `y`. Проверьте, найдя скалярное произведение вектора (0,2) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)

In [111]:
def Prod(x,y):
    x = np.array(x).transpose()
    y = np.array(y)
    return x.dot(y)[0,0]
vec = np.array([[0],[2]])
vec2 = np.array([[3],[5]])
vec3 = np.array([[-5],[3]])
Prod(vec2,vec3)

0

# 5. Метод Гаусса
Пусть имеется матрица 3x4 
    
    A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

Получите с помощью операций над слайсами результат зануления элементов в первом столбце на первом шаге метода Гаусса

In [112]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])
A[1] = A[1] - 2*A[0]
A[2] = A[2] - 3*A[0]
A

array([[ 1,  2,  0, -1],
       [ 0, -1,  1,  6],
       [ 0, -3,  3,  6]])

# 6. Получите тот же результат из исходного A путем умножения на две матрицы слева

In [116]:
arr1 = np.zeros_like(A)
arr1[0,0] = 1
arr1

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 7. Возьмите квадратную матрицу B - три первых столбца матрицы A и постройте ее LU-разложение