In [1]:
import numpy as np

In [2]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [3]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [4]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [5]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [6]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [7]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [10]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец v, с координатами 0 по иксу, 2 по игреку. Вычислите вектор-столбец w как результат поворота v на 30 градусов при помощи матрицы R

In [15]:
v = np.array([0,2]).reshape(2,1)
w = R.dot(v)
w

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R.

In [19]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию `Prod(x,y)`, которая вовращает скалярное произведение векоторов-столбцов `x` и `y`. Проверьте, найдя скалярное произведение вектора (0,2) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)

In [33]:
def prod(x,y):
    x=np.array.transpose
    y=np.array
    return x.dot(y)[0,0]
v1=np.array([[3],[5]])
v2=np.array([[-5],[3]])
prod(v1,v2)

    
    

AttributeError: 'builtin_function_or_method' object has no attribute 'transpose'

# 5. Метод Гаусса
Пусть имеется матрица 3x4 
    
    A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

Получите с помощью операций над слайсами результат зануления элементов в первом столбце на первом шаге метода Гаусса

In [8]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 3,  3,  3,  3]])

# 6. Получите тот же результат из исходного A путем умножения на две матрицы слева

# 7. Возьмите квадратную матрицу B - три первых столбца матрицы A и постройте ее LU-разложение