In [2]:
import numpy as np

In [3]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [4]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [5]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [6]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [7]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [8]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [12]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец v, с координатами 0 по иксу, 2 по игреку. Вычислите вектор-столбец w как результат поворота v на 30 градусов при помощи матрицы R

In [14]:
v = np.array([[0],[2]])
w = R.dot(v)
w

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R.

In [20]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию `Prod(x,y)`, которая вовращает скалярное произведение векоторов-столбцов `x` и `y`. Проверьте, найдя скалярное произведение вектора (0,2) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)

In [34]:
def prod (x,y):
    x = np.array(x)
    y = np.array(y)
    return x,y
np.array([0][2]).transpos

IndexError: list index out of range

# 5. Метод Гаусса
Пусть имеется матрица 3x4 
    
    A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

Получите с помощью операций над слайсами результат зануления элементов в первом столбце на первом шаге метода Гаусса

In [27]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])
A[0]
A[0]*[0]

array([0, 0, 0, 0])

# 6. Получите тот же результат из исходного A путем умножения на две матрицы слева

# 7. Возьмите квадратную матрицу B - три первых столбца матрицы A и постройте ее LU-разложение