In [58]:
import numpy as np

In [59]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],
              [np.sin(np.pi/6), np.cos(np.pi/6)]])
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [60]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [61]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [62]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец v, с координатами 0 по иксу, 2 по игреку. Вычислите вектор-столбец w как результат поворота v на 30 градусов при помощи матрицы R

In [68]:
v = np.array([[0],[2]])
w = R.dot(v)
w

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R.

In [69]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию `Prod(x,y)`, которая вовращает скалярное произведение векоторов-столбцов `x` и `y`. Проверьте, найдя скалярное произведение вектора (0,2) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)

In [63]:
def Prod(x,y):
    return x.T.dot(y)[0,0]
    
    

In [64]:
x = np.array([ [3],[5]])
y = np.array([[-5],[3]])
z = np.array([ [0],[2]])

Prod(z,z)

4

In [65]:
np.random.rand(20)

array([0.57757129, 0.93146885, 0.40375473, 0.68189669, 0.66734512,
       0.19410674, 0.80871512, 0.27601426, 0.7536    , 0.76684459,
       0.21087275, 0.81568332, 0.15135517, 0.81590008, 0.55510456,
       0.85405308, 0.25453764, 0.03592794, 0.38275676, 0.70767106])

In [66]:
from matplotlib import pyplot as plt

In [67]:
plt.figure(figsize=(10,4))
plt.title()
plt.plot(f)

TypeError: title() missing 1 required positional argument: 's'

<Figure size 720x288 with 0 Axes>

# 5. Метод Гаусса
Пусть имеется матрица 3x4 
    
    A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

Получите с помощью операций над слайсами результат зануления элементов в первом столбце на первом шаге метода Гаусса

In [79]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,4]])
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 3,  3,  3,  4]])

In [80]:
A[1]

array([2, 3, 1, 4])

In [81]:
A[2] = A[2]-3*A[0]
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 0, -3,  3,  7]])

In [55]:
A[2] = .....
A

SyntaxError: invalid syntax (<ipython-input-55-8639b4de8c96>, line 1)

# 6. Получите тот же результат из исходного A путем умножения на две матрицы слева

# 7. Возьмите квадратную матрицу B - три первых столбца матрицы A и постройте ее LU-разложение